import { config } from "dotenv";
config({ path: ".env.local" });
config({ path: ".env" });

// Author Watch — orquestador diario. Lee el JSON que dejó scrape-author.py,
// inserta los tweets en author_tweets (con cashtags extraídos), y genera el
// author brief del día. Pensado para el LaunchAgent com.catalyst.author
// (1×/día 12:00) y para runs manuales.
//
//   pnpm exec tsx scripts/author-daily.ts <handle> <tweets.json>
//
// El scraping (Python + cookies Brave) se hace ANTES por el wrapper; este
// script no toca X — solo BD + LLM.

import { readFileSync } from "node:fs";
import { sql } from "drizzle-orm";

// Cashtags $XYZ del texto del tweet. El $ literal es intención fuerte. Filtra
// longitudes 1-5, mayúsculas. No dependemos del extractor de noticias (ese
// asume shape de headline + aliases de BD); en tweets el cashtag es la señal.
function extractCashtags(text: string): string[] {
  const out = new Set<string>();
  for (const m of text.matchAll(/\$([A-Za-z]{1,5})(?![A-Za-z])/g)) {
    out.add(m[1].toUpperCase());
  }
  return [...out];
}

async function main() {
  const handle = (process.argv[2] ?? "Couch_Investor").replace(/^@/, "");
  const jsonPath = process.argv[3] ?? "/tmp/catalyst-author-tweets.json";

  const { db } = await import("../lib/db");

  let payload: { tweets?: Array<Record<string, unknown>>; error?: string };
  try {
    payload = JSON.parse(readFileSync(jsonPath, "utf8"));
  } catch (e) {
    console.error(`[author-daily] cannot read ${jsonPath}:`, e);
    process.exit(1);
  }
  if (payload.error) {
    console.warn(`[author-daily] scraper reported: ${payload.error} — keeping previous brief`);
    process.exit(0);
  }
  const tweets = payload.tweets ?? [];
  if (!tweets.length) {
    console.warn("[author-daily] no tweets in payload — nothing to ingest");
    process.exit(0);
  }

  // Upsert de tweets. Idempotente por tweet_id (PK). Actualiza texto/tickers
  // por si un tweet se editó entre pasadas.
  let inserted = 0;
  let skipped = 0;
  for (const t of tweets) {
    const text = String(t.text ?? "");
    const tickers = extractCashtags(text);
    // Postgres text[] literal via ARRAY[...]; el execute crudo del driver Neon
    // no serializa arrays JS. sql.join arma ARRAY['A','B'] (o ARRAY[]::text[]).
    const tickerArray = tickers.length
      ? sql`ARRAY[${sql.join(
          tickers.map((s) => sql`${s}`),
          sql`, `,
        )}]::text[]`
      : sql`ARRAY[]::text[]`;
    // Guard por tweet: un created_at que falle el cast ::timestamptz (o
    // cualquier fila corrupta del scraper) NO debe abortar el ingest entero
    // ni saltarse el brief. Lo saltamos y seguimos.
    try {
      await db.execute(sql`
        INSERT INTO author_tweets
          (tweet_id, author, text, created_at, url, is_retweet, tickers, fetched_at)
        VALUES (
          ${String(t.tweet_id)}, ${handle}, ${text},
          ${String(t.created_at)}::timestamptz, ${t.url ? String(t.url) : null},
          ${Number(t.is_retweet ?? 0)}, ${tickerArray}, now()
        )
        ON CONFLICT (tweet_id) DO UPDATE SET
          text = EXCLUDED.text, tickers = EXCLUDED.tickers, fetched_at = now()
      `);
      inserted++;
    } catch (e) {
      skipped++;
      console.warn(
        `[author-daily] skipped tweet ${t.tweet_id}:`,
        e instanceof Error ? e.message.slice(0, 100) : e,
      );
    }
  }
  console.log(
    `[author-daily] ${handle}: upserted ${inserted} tweets${skipped ? ` (${skipped} skipped)` : ""}`,
  );

  // Genera el brief del día.
  try {
    const { generateAuthorBrief } = await import("../lib/ai/author-brief");
    const brief = await generateAuthorBrief(handle);
    console.log(
      `[author-daily] brief generated by ${brief.model}: ${brief.content.stocks.length} stocks, covered ${brief.coveredDate}`,
    );
    console.log(`  intro: ${brief.content.intro}`);
    for (const s of brief.content.stocks) {
      console.log(`  ■ ${s.symbol}: ${s.authorTake}`);
      if (s.divergence) console.log(`    ⚠ divergence: ${s.divergence}`);
    }
  } catch (err) {
    console.warn(
      "[author-daily] brief generation failed (keeping previous):",
      err instanceof Error ? err.message : err,
    );
  }
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error("[author-daily] FATAL:", e instanceof Error ? e.message : e);
    process.exit(1);
  });
