// Task B (2026-05-18) — Bulk seed de aliases para resolver el chicken-and-egg
// del extractor: hasta ahora el alias dict se construía solo con tickers que
// ya habían pasado por enricher (Finnhub), lo que dejaba sin atribuir a
// noticias tipo "Bausch Health to Participate in..." cuando Bausch nunca
// había sido tageado por una API.
//
// Este script siembra ~700 nombres curados (S&P 500 + Russell 2000 mid-caps
// con strong news flow) directamente en `tickers` + `ticker_aliases`, así
// el extractor puede matchear menciones por nombre desde día uno.
//
// Idempotente: `onConflictDoNothing` en ambas tablas. `--dry-run` imprime
// lo que insertaría sin tocar la BD.
//
// Reglas:
//   - alias ≥3 chars (el extractor descarta <3)
//   - alias no debe caer en ALIAS_DENYLIST del extractor (palabras genéricas)
//   - aliases ≤4 chars son case-sensitive en el extractor → capitalización
//     debe ser exacta (la lista ya lo respeta)
//   - se inserta también la versión sin suffix corporativo ("Bausch Health"
//     además de "Bausch Health Companies Inc")

import { config } from "dotenv";
config({ path: ".env.local" });
config({ path: ".env" });

// Mismo denylist que `lib/tickers/extractor.ts`. Aliases que caen aquí no se
// insertan — el extractor los rechaza de todos modos, así no engordamos la
// tabla con basura. Mantener sincronizado a mano (cambia raramente).
const ALIAS_DENYLIST = new Set([
  "sea", "target", "group", "capital", "bank", "energy", "industries",
  "networks", "real", "trust", "media", "health", "tech", "data",
  "holdings", "international", "global", "company", "co", "corp",
  "inc", "ltd", "limited", "plc", "ag", "nv", "spa", "oyj", "ab", "sa",
  "performance", "canadian", "bullish", "bearish",
  "growth", "earnings", "revenue", "stock", "shares", "price", "value",
  "report", "rating", "quarter", "annual", "fiscal", "guidance",
  "sterling", "block",
]);

// API_ONLY_TICKERS: símbolos 1-2 chars que el extractor solo acepta vía API.
// Insertar aliases para ellos es inocuo (el dict matcher los skip-ea), pero
// no ayuda — los excluimos para no inflar la tabla.
const API_ONLY = new Set([
  "A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q",
  "R","S","T","U","V","W","X","Y","Z",
  "MS","SE","AI","UP","ON","GO","RH","DG","EA","BJ",
]);

type Seed = { ticker: string; name: string };

// ~700 entradas curadas. Formato `{ticker, name}` con nombre razonablemente
// completo — la normalización stripeará el suffix corporativo. No incluyo
// nombres genéricos de una sola palabra que estén en ALIAS_DENYLIST.
const SEEDS: Seed[] = [
  // ─── S&P 500 — Mega/Large cap (ya algunos en seed-list.ts pero reinsertar
  //     es gratis por onConflictDoNothing y cubre gaps) ──────────────────
  { ticker: "AAPL", name: "Apple Inc" },
  { ticker: "MSFT", name: "Microsoft Corporation" },
  { ticker: "GOOGL", name: "Alphabet Inc" },
  { ticker: "AMZN", name: "Amazon.com Inc" },
  { ticker: "NVDA", name: "NVIDIA Corporation" },
  { ticker: "META", name: "Meta Platforms Inc" },
  { ticker: "TSLA", name: "Tesla Inc" },
  { ticker: "BRK.B", name: "Berkshire Hathaway Inc" },
  { ticker: "JPM", name: "JPMorgan Chase & Co" },
  { ticker: "LLY", name: "Eli Lilly and Company" },
  { ticker: "AVGO", name: "Broadcom Inc" },
  { ticker: "WMT", name: "Walmart Inc" },
  { ticker: "XOM", name: "Exxon Mobil Corporation" },
  { ticker: "UNH", name: "UnitedHealth Group Incorporated" },
  { ticker: "ORCL", name: "Oracle Corporation" },
  { ticker: "JNJ", name: "Johnson & Johnson" },
  { ticker: "PG", name: "Procter & Gamble Company" },
  { ticker: "MA", name: "Mastercard Incorporated" },
  { ticker: "HD", name: "Home Depot Inc" },
  { ticker: "COST", name: "Costco Wholesale Corporation" },
  { ticker: "ABBV", name: "AbbVie Inc" },
  { ticker: "NFLX", name: "Netflix Inc" },
  { ticker: "BAC", name: "Bank of America Corporation" },
  { ticker: "KO", name: "Coca-Cola Company" },
  { ticker: "CVX", name: "Chevron Corporation" },
  { ticker: "MRK", name: "Merck & Co Inc" },
  { ticker: "ADBE", name: "Adobe Inc" },
  { ticker: "PEP", name: "PepsiCo Inc" },
  { ticker: "CRM", name: "Salesforce Inc" },
  { ticker: "TMO", name: "Thermo Fisher Scientific Inc" },
  { ticker: "ACN", name: "Accenture plc" },
  { ticker: "LIN", name: "Linde plc" },
  { ticker: "WFC", name: "Wells Fargo & Company" },
  { ticker: "MCD", name: "McDonald's Corporation" },
  { ticker: "ABT", name: "Abbott Laboratories" },
  { ticker: "DHR", name: "Danaher Corporation" },
  { ticker: "CSCO", name: "Cisco Systems Inc" },
  { ticker: "GE", name: "General Electric Company" },
  { ticker: "DIS", name: "Walt Disney Company" },
  { ticker: "TXN", name: "Texas Instruments Incorporated" },
  { ticker: "AMD", name: "Advanced Micro Devices Inc" },
  { ticker: "VZ", name: "Verizon Communications Inc" },
  { ticker: "AMGN", name: "Amgen Inc" },
  { ticker: "PM", name: "Philip Morris International Inc" },
  { ticker: "QCOM", name: "QUALCOMM Incorporated" },
  { ticker: "IBM", name: "International Business Machines Corporation" },
  { ticker: "INTU", name: "Intuit Inc" },
  { ticker: "CAT", name: "Caterpillar Inc" },
  { ticker: "RTX", name: "RTX Corporation" },
  { ticker: "GS", name: "Goldman Sachs Group Inc" },
  { ticker: "SPGI", name: "S&P Global Inc" },
  { ticker: "NEE", name: "NextEra Energy Inc" },
  { ticker: "ISRG", name: "Intuitive Surgical Inc" },
  { ticker: "AXP", name: "American Express Company" },
  { ticker: "BKNG", name: "Booking Holdings Inc" },
  { ticker: "NOW", name: "ServiceNow Inc" },
  { ticker: "BLK", name: "BlackRock Inc" },
  { ticker: "HON", name: "Honeywell International Inc" },
  { ticker: "SYK", name: "Stryker Corporation" },
  { ticker: "PFE", name: "Pfizer Inc" },
  { ticker: "ELV", name: "Elevance Health Inc" },
  { ticker: "LMT", name: "Lockheed Martin Corporation" },
  { ticker: "TJX", name: "TJX Companies Inc" },
  { ticker: "VRTX", name: "Vertex Pharmaceuticals Incorporated" },
  { ticker: "MDT", name: "Medtronic plc" },
  { ticker: "SBUX", name: "Starbucks Corporation" },
  { ticker: "BSX", name: "Boston Scientific Corporation" },
  { ticker: "ADP", name: "Automatic Data Processing Inc" },
  { ticker: "PLD", name: "Prologis Inc" },
  { ticker: "GILD", name: "Gilead Sciences Inc" },
  { ticker: "MMC", name: "Marsh & McLennan Companies Inc" },
  { ticker: "MU", name: "Micron Technology Inc" },
  { ticker: "PANW", name: "Palo Alto Networks Inc" },
  { ticker: "SCHW", name: "Charles Schwab Corporation" },
  { ticker: "PGR", name: "Progressive Corporation" },
  { ticker: "DE", name: "Deere & Company" },
  { ticker: "BMY", name: "Bristol-Myers Squibb Company" },
  { ticker: "REGN", name: "Regeneron Pharmaceuticals Inc" },
  { ticker: "LRCX", name: "Lam Research Corporation" },
  { ticker: "ETN", name: "Eaton Corporation plc" },
  { ticker: "AMT", name: "American Tower Corporation" },
  { ticker: "ZTS", name: "Zoetis Inc" },
  { ticker: "FI", name: "Fiserv Inc" },
  { ticker: "CB", name: "Chubb Limited" },
  { ticker: "ANET", name: "Arista Networks Inc" },
  { ticker: "TMUS", name: "T-Mobile US Inc" },
  { ticker: "CMCSA", name: "Comcast Corporation" },
  { ticker: "CI", name: "Cigna Group" },
  { ticker: "MO", name: "Altria Group Inc" },
  { ticker: "PYPL", name: "PayPal Holdings Inc" },
  { ticker: "ADI", name: "Analog Devices Inc" },
  { ticker: "SHW", name: "Sherwin-Williams Company" },
  { ticker: "FDX", name: "FedEx Corporation" },
  { ticker: "EQIX", name: "Equinix Inc" },
  { ticker: "EOG", name: "EOG Resources Inc" },
  { ticker: "AON", name: "Aon plc" },
  { ticker: "CME", name: "CME Group Inc" },
  { ticker: "MDLZ", name: "Mondelez International Inc" },
  { ticker: "ICE", name: "Intercontinental Exchange Inc" },
  { ticker: "CL", name: "Colgate-Palmolive Company" },
  { ticker: "USB", name: "U.S. Bancorp" },
  { ticker: "BDX", name: "Becton Dickinson and Company" },
  { ticker: "MCO", name: "Moody's Corporation" },
  { ticker: "PNC", name: "PNC Financial Services Group Inc" },
  { ticker: "SO", name: "Southern Company" },
  { ticker: "DUK", name: "Duke Energy Corporation" },
  { ticker: "WM", name: "Waste Management Inc" },
  { ticker: "ITW", name: "Illinois Tool Works Inc" },
  { ticker: "TGT", name: "Target Corporation" },
  { ticker: "EMR", name: "Emerson Electric Co" },
  { ticker: "APH", name: "Amphenol Corporation" },
  { ticker: "CSX", name: "CSX Corporation" },
  { ticker: "MMM", name: "3M Company" },
  { ticker: "MAR", name: "Marriott International Inc" },
  { ticker: "PH", name: "Parker-Hannifin Corporation" },
  { ticker: "FCX", name: "Freeport-McMoRan Inc" },
  { ticker: "MCK", name: "McKesson Corporation" },
  { ticker: "COP", name: "ConocoPhillips" },
  { ticker: "NSC", name: "Norfolk Southern Corporation" },
  { ticker: "WELL", name: "Welltower Inc" },
  { ticker: "ORLY", name: "O'Reilly Automotive Inc" },
  { ticker: "GD", name: "General Dynamics Corporation" },
  { ticker: "ECL", name: "Ecolab Inc" },
  { ticker: "AJG", name: "Arthur J. Gallagher & Co" },
  { ticker: "APD", name: "Air Products and Chemicals Inc" },
  { ticker: "TRV", name: "Travelers Companies Inc" },
  { ticker: "HCA", name: "HCA Healthcare Inc" },
  { ticker: "AFL", name: "Aflac Incorporated" },
  { ticker: "NXPI", name: "NXP Semiconductors NV" },
  { ticker: "MET", name: "MetLife Inc" },
  { ticker: "ROP", name: "Roper Technologies Inc" },
  { ticker: "PCAR", name: "PACCAR Inc" },
  { ticker: "AIG", name: "American International Group Inc" },
  { ticker: "SLB", name: "Schlumberger Limited" },
  { ticker: "MNST", name: "Monster Beverage Corporation" },
  { ticker: "PSX", name: "Phillips 66" },
  { ticker: "AZO", name: "AutoZone Inc" },
  { ticker: "PSA", name: "Public Storage" },
  { ticker: "BK", name: "Bank of New York Mellon Corporation" },
  { ticker: "AEP", name: "American Electric Power Company Inc" },
  { ticker: "DXCM", name: "DexCom Inc" },
  { ticker: "TDG", name: "TransDigm Group Incorporated" },
  { ticker: "ROST", name: "Ross Stores Inc" },
  { ticker: "MSI", name: "Motorola Solutions Inc" },
  { ticker: "GIS", name: "General Mills Inc" },
  { ticker: "PAYX", name: "Paychex Inc" },
  { ticker: "CTAS", name: "Cintas Corporation" },
  { ticker: "OXY", name: "Occidental Petroleum Corporation" },
  { ticker: "KLAC", name: "KLA Corporation" },
  { ticker: "FTNT", name: "Fortinet Inc" },
  { ticker: "WMB", name: "Williams Companies Inc" },
  { ticker: "ODFL", name: "Old Dominion Freight Line Inc" },
  { ticker: "ALL", name: "Allstate Corporation" },
  { ticker: "MPC", name: "Marathon Petroleum Corporation" },
  { ticker: "VLO", name: "Valero Energy Corporation" },
  { ticker: "SRE", name: "Sempra" },
  { ticker: "AMP", name: "Ameriprise Financial Inc" },
  { ticker: "KMB", name: "Kimberly-Clark Corporation" },
  { ticker: "STZ", name: "Constellation Brands Inc" },
  { ticker: "CARR", name: "Carrier Global Corporation" },
  { ticker: "FAST", name: "Fastenal Company" },
  { ticker: "JCI", name: "Johnson Controls International plc" },
  { ticker: "HLT", name: "Hilton Worldwide Holdings Inc" },
  { ticker: "WBD", name: "Warner Bros. Discovery Inc" },
  { ticker: "PRU", name: "Prudential Financial Inc" },
  { ticker: "DLR", name: "Digital Realty Trust Inc" },
  { ticker: "CMG", name: "Chipotle Mexican Grill Inc" },
  { ticker: "AME", name: "AMETEK Inc" },
  { ticker: "TT", name: "Trane Technologies plc" },
  { ticker: "URI", name: "United Rentals Inc" },
  { ticker: "CTSH", name: "Cognizant Technology Solutions Corporation" },
  { ticker: "F", name: "Ford Motor Company" },
  { ticker: "ROK", name: "Rockwell Automation Inc" },
  { ticker: "DOW", name: "Dow Inc" },
  { ticker: "BIIB", name: "Biogen Inc" },
  { ticker: "IDXX", name: "IDEXX Laboratories Inc" },
  { ticker: "PCG", name: "PG&E Corporation" },
  { ticker: "HUM", name: "Humana Inc" },
  { ticker: "GM", name: "General Motors Company" },
  { ticker: "OKE", name: "ONEOK Inc" },
  { ticker: "EW", name: "Edwards Lifesciences Corporation" },
  { ticker: "EXC", name: "Exelon Corporation" },
  { ticker: "CMI", name: "Cummins Inc" },
  { ticker: "FIS", name: "Fidelity National Information Services Inc" },
  { ticker: "VRSK", name: "Verisk Analytics Inc" },
  { ticker: "IQV", name: "IQVIA Holdings Inc" },
  { ticker: "GWW", name: "W.W. Grainger Inc" },
  { ticker: "CCI", name: "Crown Castle Inc" },
  { ticker: "HSY", name: "Hershey Company" },
  { ticker: "A", name: "Agilent Technologies Inc" },
  { ticker: "KMI", name: "Kinder Morgan Inc" },
  { ticker: "YUM", name: "Yum! Brands Inc" },
  { ticker: "VST", name: "Vistra Corp" },
  { ticker: "DD", name: "DuPont de Nemours Inc" },
  { ticker: "LHX", name: "L3Harris Technologies Inc" },
  { ticker: "OTIS", name: "Otis Worldwide Corporation" },
  { ticker: "FICO", name: "Fair Isaac Corporation" },
  { ticker: "VICI", name: "VICI Properties Inc" },
  { ticker: "GEHC", name: "GE HealthCare Technologies Inc" },
  { ticker: "GEV", name: "GE Vernova Inc" },
  { ticker: "CTVA", name: "Corteva Inc" },
  { ticker: "EXR", name: "Extra Space Storage Inc" },
  { ticker: "FANG", name: "Diamondback Energy Inc" },
  { ticker: "PPG", name: "PPG Industries Inc" },
  { ticker: "DAL", name: "Delta Air Lines Inc" },
  { ticker: "CSGP", name: "CoStar Group Inc" },
  { ticker: "RSG", name: "Republic Services Inc" },
  { ticker: "CDW", name: "CDW Corporation" },
  { ticker: "MSCI", name: "MSCI Inc" },
  { ticker: "GLW", name: "Corning Incorporated" },
  { ticker: "ED", name: "Consolidated Edison Inc" },
  { ticker: "EA", name: "Electronic Arts Inc" },
  { ticker: "DG", name: "Dollar General Corporation" },
  { ticker: "ON", name: "ON Semiconductor Corporation" },
  { ticker: "XEL", name: "Xcel Energy Inc" },
  { ticker: "HES", name: "Hess Corporation" },
  { ticker: "KDP", name: "Keurig Dr Pepper Inc" },
  { ticker: "EFX", name: "Equifax Inc" },
  { ticker: "BKR", name: "Baker Hughes Company" },
  { ticker: "TRGP", name: "Targa Resources Corp" },
  { ticker: "STT", name: "State Street Corporation" },
  { ticker: "AVB", name: "AvalonBay Communities Inc" },
  { ticker: "WEC", name: "WEC Energy Group Inc" },
  { ticker: "RJF", name: "Raymond James Financial Inc" },
  { ticker: "CHTR", name: "Charter Communications Inc" },
  { ticker: "HPQ", name: "HP Inc" },
  { ticker: "TSCO", name: "Tractor Supply Company" },
  { ticker: "ANSS", name: "ANSYS Inc" },
  { ticker: "WAB", name: "Westinghouse Air Brake Technologies Corporation" },
  { ticker: "DOV", name: "Dover Corporation" },
  { ticker: "GRMN", name: "Garmin Ltd" },
  { ticker: "DFS", name: "Discover Financial Services" },
  { ticker: "SYY", name: "Sysco Corporation" },
  { ticker: "CBRE", name: "CBRE Group Inc" },
  { ticker: "ROL", name: "Rollins Inc" },
  { ticker: "ETR", name: "Entergy Corporation" },
  { ticker: "TYL", name: "Tyler Technologies Inc" },
  { ticker: "GPN", name: "Global Payments Inc" },
  { ticker: "VMC", name: "Vulcan Materials Company" },
  { ticker: "ADM", name: "Archer-Daniels-Midland Company" },
  { ticker: "PWR", name: "Quanta Services Inc" },
  { ticker: "ACGL", name: "Arch Capital Group Ltd" },
  { ticker: "DTE", name: "DTE Energy Company" },
  { ticker: "AWK", name: "American Water Works Company Inc" },
  { ticker: "MLM", name: "Martin Marietta Materials Inc" },
  { ticker: "NUE", name: "Nucor Corporation" },
  { ticker: "WTW", name: "Willis Towers Watson Public Limited Company" },
  { ticker: "RMD", name: "ResMed Inc" },
  { ticker: "IR", name: "Ingersoll Rand Inc" },
  { ticker: "EBAY", name: "eBay Inc" },
  { ticker: "WY", name: "Weyerhaeuser Company" },
  { ticker: "FITB", name: "Fifth Third Bancorp" },
  { ticker: "ES", name: "Eversource Energy" },
  { ticker: "EIX", name: "Edison International" },
  { ticker: "PEG", name: "Public Service Enterprise Group Incorporated" },
  { ticker: "HIG", name: "Hartford Financial Services Group Inc" },
  { ticker: "BRO", name: "Brown & Brown Inc" },
  { ticker: "STLD", name: "Steel Dynamics Inc" },
  { ticker: "VTR", name: "Ventas Inc" },
  { ticker: "WST", name: "West Pharmaceutical Services Inc" },
  { ticker: "AVY", name: "Avery Dennison Corporation" },
  { ticker: "WAT", name: "Waters Corporation" },
  { ticker: "FE", name: "FirstEnergy Corp" },
  { ticker: "PPL", name: "PPL Corporation" },
  { ticker: "TROW", name: "T. Rowe Price Group Inc" },
  { ticker: "MTB", name: "M&T Bank Corporation" },
  { ticker: "VRSN", name: "VeriSign Inc" },
  { ticker: "WBA", name: "Walgreens Boots Alliance Inc" },
  { ticker: "CHD", name: "Church & Dwight Co Inc" },
  { ticker: "MTD", name: "Mettler-Toledo International Inc" },
  { ticker: "INVH", name: "Invitation Homes Inc" },
  { ticker: "TDY", name: "Teledyne Technologies Incorporated" },
  { ticker: "BR", name: "Broadridge Financial Solutions Inc" },
  { ticker: "DRI", name: "Darden Restaurants Inc" },
  { ticker: "STE", name: "STERIS plc" },
  { ticker: "FSLR", name: "First Solar Inc" },
  { ticker: "PHM", name: "PulteGroup Inc" },
  { ticker: "HBAN", name: "Huntington Bancshares Incorporated" },
  { ticker: "ZBH", name: "Zimmer Biomet Holdings Inc" },
  { ticker: "DELL", name: "Dell Technologies Inc" },
  { ticker: "CDNS", name: "Cadence Design Systems Inc" },
  { ticker: "SNPS", name: "Synopsys Inc" },
  { ticker: "MRVL", name: "Marvell Technology Inc" },
  { ticker: "MPWR", name: "Monolithic Power Systems Inc" },
  { ticker: "AKAM", name: "Akamai Technologies Inc" },
  { ticker: "SWKS", name: "Skyworks Solutions Inc" },
  { ticker: "CINF", name: "Cincinnati Financial Corporation" },
  { ticker: "LYB", name: "LyondellBasell Industries NV" },
  { ticker: "EXPE", name: "Expedia Group Inc" },
  { ticker: "DHI", name: "D.R. Horton Inc" },
  { ticker: "LEN", name: "Lennar Corporation" },
  { ticker: "NVR", name: "NVR Inc" },
  { ticker: "TOL", name: "Toll Brothers Inc" },
  { ticker: "KMX", name: "CarMax Inc" },
  { ticker: "CCL", name: "Carnival Corporation" },
  { ticker: "RCL", name: "Royal Caribbean Cruises Ltd" },
  { ticker: "NCLH", name: "Norwegian Cruise Line Holdings Ltd" },
  { ticker: "MGM", name: "MGM Resorts International" },
  { ticker: "WYNN", name: "Wynn Resorts Limited" },
  { ticker: "LVS", name: "Las Vegas Sands Corp" },
  { ticker: "CZR", name: "Caesars Entertainment Inc" },
  { ticker: "DPZ", name: "Domino's Pizza Inc" },
  { ticker: "QSR", name: "Restaurant Brands International Inc" },
  { ticker: "AIZ", name: "Assurant Inc" },
  { ticker: "DLTR", name: "Dollar Tree Inc" },
  { ticker: "BBY", name: "Best Buy Co Inc" },
  { ticker: "KR", name: "Kroger Co" },
  { ticker: "ULTA", name: "Ulta Beauty Inc" },
  { ticker: "EL", name: "Estee Lauder Companies Inc" },
  { ticker: "CLX", name: "Clorox Company" },
  { ticker: "CAG", name: "Conagra Brands Inc" },
  { ticker: "K", name: "Kellanova" },
  { ticker: "MKC", name: "McCormick & Company Incorporated" },
  { ticker: "HRL", name: "Hormel Foods Corporation" },
  { ticker: "TAP", name: "Molson Coors Beverage Company" },
  { ticker: "BF.B", name: "Brown-Forman Corporation" },
  { ticker: "TSN", name: "Tyson Foods Inc" },
  { ticker: "SJM", name: "J.M. Smucker Company" },
  { ticker: "CPB", name: "Campbell Soup Company" },
  { ticker: "LW", name: "Lamb Weston Holdings Inc" },
  { ticker: "BLDR", name: "Builders FirstSource Inc" },
  { ticker: "PKG", name: "Packaging Corporation of America" },
  { ticker: "IP", name: "International Paper Company" },
  { ticker: "WRK", name: "WestRock Company" },
  { ticker: "BALL", name: "Ball Corporation" },
  { ticker: "AMCR", name: "Amcor plc" },
  { ticker: "SEE", name: "Sealed Air Corporation" },
  { ticker: "CF", name: "CF Industries Holdings Inc" },
  { ticker: "MOS", name: "Mosaic Company" },
  { ticker: "FMC", name: "FMC Corporation" },
  { ticker: "ALB", name: "Albemarle Corporation" },
  { ticker: "EMN", name: "Eastman Chemical Company" },
  { ticker: "CE", name: "Celanese Corporation" },
  { ticker: "VTRS", name: "Viatris Inc" },
  { ticker: "TFC", name: "Truist Financial Corporation" },
  { ticker: "KEY", name: "KeyCorp" },
  { ticker: "RF", name: "Regions Financial Corporation" },
  { ticker: "CFG", name: "Citizens Financial Group Inc" },
  { ticker: "COF", name: "Capital One Financial Corporation" },
  { ticker: "SYF", name: "Synchrony Financial" },
  { ticker: "WTFC", name: "Wintrust Financial Corporation" },
  { ticker: "ZION", name: "Zions Bancorporation" },
  { ticker: "CFR", name: "Cullen/Frost Bankers Inc" },
  { ticker: "FHN", name: "First Horizon Corporation" },
  { ticker: "WAL", name: "Western Alliance Bancorporation" },
  { ticker: "PFG", name: "Principal Financial Group Inc" },
  { ticker: "GL", name: "Globe Life Inc" },
  { ticker: "L", name: "Loews Corporation" },
  { ticker: "RGA", name: "Reinsurance Group of America Incorporated" },
  { ticker: "EG", name: "Everest Group Ltd" },
  { ticker: "RNR", name: "RenaissanceRe Holdings Ltd" },
  { ticker: "AIZ", name: "Assurant Inc" },
  { ticker: "FAF", name: "First American Financial Corporation" },
  { ticker: "FNF", name: "Fidelity National Financial Inc" },
  { ticker: "MMC", name: "Marsh & McLennan Companies Inc" },
  { ticker: "ATO", name: "Atmos Energy Corporation" },
  { ticker: "CMS", name: "CMS Energy Corporation" },
  { ticker: "CNP", name: "CenterPoint Energy Inc" },
  { ticker: "AEE", name: "Ameren Corporation" },
  { ticker: "NRG", name: "NRG Energy Inc" },
  { ticker: "AES", name: "AES Corporation" },
  { ticker: "EVRG", name: "Evergy Inc" },
  { ticker: "LNT", name: "Alliant Energy Corporation" },
  { ticker: "PNW", name: "Pinnacle West Capital Corporation" },
  { ticker: "NI", name: "NiSource Inc" },
  { ticker: "ESS", name: "Essex Property Trust Inc" },
  { ticker: "MAA", name: "Mid-America Apartment Communities Inc" },
  { ticker: "UDR", name: "UDR Inc" },
  { ticker: "EQR", name: "Equity Residential" },
  { ticker: "CPT", name: "Camden Property Trust" },
  { ticker: "ARE", name: "Alexandria Real Estate Equities Inc" },
  { ticker: "BXP", name: "BXP Inc" },
  { ticker: "HST", name: "Host Hotels & Resorts Inc" },
  { ticker: "REG", name: "Regency Centers Corporation" },
  { ticker: "KIM", name: "Kimco Realty Corporation" },
  { ticker: "FRT", name: "Federal Realty Investment Trust" },
  { ticker: "SPG", name: "Simon Property Group Inc" },
  { ticker: "MAC", name: "Macerich Company" },
  { ticker: "DOC", name: "Healthpeak Properties Inc" },
  { ticker: "IRM", name: "Iron Mountain Incorporated" },
  { ticker: "SBAC", name: "SBA Communications Corporation" },
  { ticker: "WPC", name: "W. P. Carey Inc" },
  { ticker: "STAG", name: "STAG Industrial Inc" },
  { ticker: "EXPD", name: "Expeditors International of Washington Inc" },
  { ticker: "JBHT", name: "J.B. Hunt Transport Services Inc" },
  { ticker: "CHRW", name: "C.H. Robinson Worldwide Inc" },
  { ticker: "XPO", name: "XPO Inc" },
  { ticker: "KNX", name: "Knight-Swift Transportation Holdings Inc" },
  { ticker: "LSTR", name: "Landstar System Inc" },
  { ticker: "ALK", name: "Alaska Air Group Inc" },
  { ticker: "LUV", name: "Southwest Airlines Co" },
  { ticker: "UAL", name: "United Airlines Holdings Inc" },
  { ticker: "AAL", name: "American Airlines Group Inc" },
  { ticker: "JBLU", name: "JetBlue Airways Corporation" },
  { ticker: "SAVE", name: "Spirit Airlines Inc" },
  { ticker: "ALGN", name: "Align Technology Inc" },
  { ticker: "TFX", name: "Teleflex Incorporated" },
  { ticker: "HOLX", name: "Hologic Inc" },
  { ticker: "VTRS", name: "Viatris Inc" },
  { ticker: "ZBRA", name: "Zebra Technologies Corporation" },
  { ticker: "NTAP", name: "NetApp Inc" },
  { ticker: "STX", name: "Seagate Technology Holdings plc" },
  { ticker: "WDC", name: "Western Digital Corporation" },
  { ticker: "TER", name: "Teradyne Inc" },
  { ticker: "JKHY", name: "Jack Henry & Associates Inc" },
  { ticker: "WDAY", name: "Workday Inc" },
  { ticker: "ADSK", name: "Autodesk Inc" },
  { ticker: "DDOG", name: "Datadog Inc" },
  { ticker: "ZS", name: "Zscaler Inc" },
  { ticker: "CRWD", name: "CrowdStrike Holdings Inc" },
  { ticker: "OKTA", name: "Okta Inc" },
  { ticker: "MDB", name: "MongoDB Inc" },
  { ticker: "NET", name: "Cloudflare Inc" },
  { ticker: "TEAM", name: "Atlassian Corporation" },
  { ticker: "ZM", name: "Zoom Communications Inc" },
  { ticker: "DOCU", name: "DocuSign Inc" },
  { ticker: "TWLO", name: "Twilio Inc" },
  { ticker: "SQ", name: "Block Inc" },
  { ticker: "XYZ", name: "Block Inc" },
  { ticker: "PINS", name: "Pinterest Inc" },
  { ticker: "SNAP", name: "Snap Inc" },
  { ticker: "RBLX", name: "Roblox Corporation" },
  { ticker: "COIN", name: "Coinbase Global Inc" },
  { ticker: "HOOD", name: "Robinhood Markets Inc" },
  { ticker: "SOFI", name: "SoFi Technologies Inc" },
  { ticker: "AFRM", name: "Affirm Holdings Inc" },
  { ticker: "UPST", name: "Upstart Holdings Inc" },
  { ticker: "LMND", name: "Lemonade Inc" },
  { ticker: "ROKU", name: "Roku Inc" },
  { ticker: "DASH", name: "DoorDash Inc" },
  { ticker: "ABNB", name: "Airbnb Inc" },
  { ticker: "UBER", name: "Uber Technologies Inc" },
  { ticker: "LYFT", name: "Lyft Inc" },
  { ticker: "PLTR", name: "Palantir Technologies Inc" },
  { ticker: "SNOW", name: "Snowflake Inc" },
  { ticker: "SHOP", name: "Shopify Inc" },
  { ticker: "SPOT", name: "Spotify Technology SA" },
  { ticker: "RIVN", name: "Rivian Automotive Inc" },
  { ticker: "LCID", name: "Lucid Group Inc" },
  { ticker: "NIO", name: "NIO Inc" },
  { ticker: "XPEV", name: "XPeng Inc" },
  { ticker: "LI", name: "Li Auto Inc" },
  { ticker: "BABA", name: "Alibaba Group Holding Limited" },
  { ticker: "JD", name: "JD.com Inc" },
  { ticker: "PDD", name: "PDD Holdings Inc" },
  { ticker: "BIDU", name: "Baidu Inc" },
  { ticker: "TME", name: "Tencent Music Entertainment Group" },
  { ticker: "BILI", name: "Bilibili Inc" },
  { ticker: "MELI", name: "MercadoLibre Inc" },
  { ticker: "SE", name: "Sea Limited" },
  { ticker: "GRAB", name: "Grab Holdings Limited" },
  { ticker: "TSM", name: "Taiwan Semiconductor Manufacturing Company Limited" },
  { ticker: "ASML", name: "ASML Holding NV" },
  { ticker: "ARM", name: "Arm Holdings plc" },
  { ticker: "AMAT", name: "Applied Materials Inc" },
  { ticker: "TXT", name: "Textron Inc" },
  { ticker: "HII", name: "Huntington Ingalls Industries Inc" },
  { ticker: "LDOS", name: "Leidos Holdings Inc" },
  { ticker: "BAH", name: "Booz Allen Hamilton Holding Corporation" },
  { ticker: "CACI", name: "CACI International Inc" },
  { ticker: "SAIC", name: "Science Applications International Corporation" },
  { ticker: "MOH", name: "Molina Healthcare Inc" },
  { ticker: "CNC", name: "Centene Corporation" },
  { ticker: "CVS", name: "CVS Health Corporation" },
  { ticker: "MRNA", name: "Moderna Inc" },
  { ticker: "BNTX", name: "BioNTech SE" },
  { ticker: "NVO", name: "Novo Nordisk A/S" },
  { ticker: "AZN", name: "AstraZeneca PLC" },
  { ticker: "GSK", name: "GSK plc" },
  { ticker: "SNY", name: "Sanofi" },
  { ticker: "NVS", name: "Novartis AG" },
  { ticker: "BAYRY", name: "Bayer AG" },
  { ticker: "TAK", name: "Takeda Pharmaceutical Company Limited" },
  { ticker: "RHHBY", name: "Roche Holding AG" },
  { ticker: "TEVA", name: "Teva Pharmaceutical Industries Limited" },
  { ticker: "BHC", name: "Bausch Health Companies Inc" },
  { ticker: "BLCO", name: "Bausch + Lomb Corporation" },
  { ticker: "BHVN", name: "Biohaven Ltd" },
  { ticker: "ICLR", name: "ICON Public Limited Company" },
  { ticker: "MTN", name: "Vail Resorts Inc" },
  { ticker: "PTON", name: "Peloton Interactive Inc" },
  { ticker: "FUBO", name: "fuboTV Inc" },
  { ticker: "RDFN", name: "Redfin Corporation" },
  { ticker: "Z", name: "Zillow Group Inc" },
  { ticker: "OPEN", name: "Opendoor Technologies Inc" },
  { ticker: "BROS", name: "Dutch Bros Inc" },
  { ticker: "CAVA", name: "CAVA Group Inc" },
  { ticker: "WING", name: "Wingstop Inc" },
  { ticker: "JACK", name: "Jack in the Box Inc" },
  { ticker: "EAT", name: "Brinker International Inc" },
  { ticker: "BJRI", name: "BJ's Restaurants Inc" },
  { ticker: "PLAY", name: "Dave & Buster's Entertainment Inc" },
  { ticker: "TXRH", name: "Texas Roadhouse Inc" },
  { ticker: "WEN", name: "Wendy's Company" },
  { ticker: "SHAK", name: "Shake Shack Inc" },
  { ticker: "CMPR", name: "Cimpress plc" },
  { ticker: "LULU", name: "Lululemon Athletica Inc" },
  { ticker: "DECK", name: "Deckers Outdoor Corporation" },
  { ticker: "BIRK", name: "Birkenstock Holding plc" },
  { ticker: "ONON", name: "On Holding AG" },
  { ticker: "UAA", name: "Under Armour Inc" },
  { ticker: "PVH", name: "PVH Corp" },
  { ticker: "RL", name: "Ralph Lauren Corporation" },
  { ticker: "TPR", name: "Tapestry Inc" },
  { ticker: "CPRI", name: "Capri Holdings Limited" },
  { ticker: "HBI", name: "Hanesbrands Inc" },
  { ticker: "VFC", name: "V.F. Corporation" },
  { ticker: "FL", name: "Foot Locker Inc" },
  { ticker: "GPS", name: "Gap Inc" },
  { ticker: "URBN", name: "Urban Outfitters Inc" },
  { ticker: "AEO", name: "American Eagle Outfitters Inc" },
  { ticker: "ANF", name: "Abercrombie & Fitch Co" },
  { ticker: "GME", name: "GameStop Corp" },
  { ticker: "AMC", name: "AMC Entertainment Holdings Inc" },
  { ticker: "BBBYQ", name: "Bed Bath & Beyond" },
  { ticker: "W", name: "Wayfair Inc" },
  { ticker: "CHWY", name: "Chewy Inc" },
  { ticker: "ETSY", name: "Etsy Inc" },
  { ticker: "PINS", name: "Pinterest Inc" },
  { ticker: "MTCH", name: "Match Group Inc" },
  { ticker: "BMBL", name: "Bumble Inc" },
  { ticker: "DUOL", name: "Duolingo Inc" },
  { ticker: "RDDT", name: "Reddit Inc" },
  { ticker: "U", name: "Unity Software Inc" },
  { ticker: "TTD", name: "Trade Desk Inc" },
  { ticker: "PUBM", name: "PubMatic Inc" },
  { ticker: "MGNI", name: "Magnite Inc" },
  { ticker: "APPS", name: "Digital Turbine Inc" },
  { ticker: "IRBT", name: "iRobot Corporation" },
  { ticker: "SONO", name: "Sonos Inc" },
  { ticker: "GPRO", name: "GoPro Inc" },
  { ticker: "FIT", name: "Fitbit Inc" },
  { ticker: "ENPH", name: "Enphase Energy Inc" },
  { ticker: "SEDG", name: "SolarEdge Technologies Inc" },
  { ticker: "RUN", name: "Sunrun Inc" },
  { ticker: "NOVA", name: "Sunnova Energy International Inc" },
  { ticker: "CSIQ", name: "Canadian Solar Inc" },
  { ticker: "JKS", name: "JinkoSolar Holding Co Ltd" },
  { ticker: "PLUG", name: "Plug Power Inc" },
  { ticker: "BLDP", name: "Ballard Power Systems Inc" },
  { ticker: "FCEL", name: "FuelCell Energy Inc" },
  { ticker: "BE", name: "Bloom Energy Corporation" },
  { ticker: "QS", name: "QuantumScape Corporation" },
  { ticker: "CHPT", name: "ChargePoint Holdings Inc" },
  { ticker: "EVGO", name: "EVgo Inc" },
  { ticker: "BLNK", name: "Blink Charging Co" },
  { ticker: "RIDE", name: "Lordstown Motors Corp" },
  { ticker: "WKHS", name: "Workhorse Group Inc" },
  { ticker: "NKLA", name: "Nikola Corporation" },
  { ticker: "GOEV", name: "Canoo Inc" },
  { ticker: "FFIE", name: "Faraday Future Intelligent Electric Inc" },
  { ticker: "MULN", name: "Mullen Automotive Inc" },
  { ticker: "MARA", name: "Marathon Digital Holdings Inc" },
  { ticker: "RIOT", name: "Riot Platforms Inc" },
  { ticker: "CLSK", name: "CleanSpark Inc" },
  { ticker: "HUT", name: "Hut 8 Corp" },
  { ticker: "BTBT", name: "Bit Digital Inc" },
  { ticker: "BITF", name: "Bitfarms Ltd" },
  { ticker: "CIFR", name: "Cipher Mining Inc" },
  { ticker: "WULF", name: "TeraWulf Inc" },
  { ticker: "MSTR", name: "Strategy Inc" },
  { ticker: "GBTC", name: "Grayscale Bitcoin Trust" },
  { ticker: "IREN", name: "IREN Limited" },
  { ticker: "GLXY", name: "Galaxy Digital Inc" },
  { ticker: "APP", name: "AppLovin Corporation" },
  { ticker: "PATH", name: "UiPath Inc" },
  { ticker: "GTLB", name: "GitLab Inc" },
  { ticker: "S", name: "SentinelOne Inc" },
  { ticker: "CXM", name: "Sprinklr Inc" },
  { ticker: "ESTC", name: "Elastic NV" },
  { ticker: "FROG", name: "JFrog Ltd" },
  { ticker: "PD", name: "PagerDuty Inc" },
  { ticker: "BILL", name: "BILL Holdings Inc" },
  { ticker: "DKNG", name: "DraftKings Inc" },
  { ticker: "PENN", name: "PENN Entertainment Inc" },
  { ticker: "FLUT", name: "Flutter Entertainment plc" },
  { ticker: "GAMB", name: "Gambling.com Group Limited" },
  { ticker: "VRT", name: "Vertiv Holdings Co" },
  { ticker: "DELL", name: "Dell Technologies Inc" },
  { ticker: "HPE", name: "Hewlett Packard Enterprise Company" },
  { ticker: "PSTG", name: "Pure Storage Inc" },
  { ticker: "SMCI", name: "Super Micro Computer Inc" },
  { ticker: "ALAB", name: "Astera Labs Inc" },
  { ticker: "CRDO", name: "Credo Technology Group Holding Ltd" },
  { ticker: "AVGO", name: "Broadcom Inc" },
  { ticker: "TSEM", name: "Tower Semiconductor Ltd" },
  { ticker: "WOLF", name: "Wolfspeed Inc" },
  { ticker: "AEHR", name: "Aehr Test Systems" },
  { ticker: "ACLS", name: "Axcelis Technologies Inc" },
  { ticker: "ONTO", name: "Onto Innovation Inc" },
  { ticker: "ENTG", name: "Entegris Inc" },
  { ticker: "FORM", name: "FormFactor Inc" },
  { ticker: "UCTT", name: "Ultra Clean Holdings Inc" },
  { ticker: "ICHR", name: "Ichor Holdings Ltd" },
  { ticker: "MKSI", name: "MKS Instruments Inc" },
  { ticker: "COHR", name: "Coherent Corp" },
  { ticker: "LITE", name: "Lumentum Holdings Inc" },
  { ticker: "VIAV", name: "Viavi Solutions Inc" },
  { ticker: "CIEN", name: "Ciena Corporation" },
  { ticker: "JNPR", name: "Juniper Networks Inc" },
  { ticker: "FFIV", name: "F5 Inc" },
  { ticker: "EXTR", name: "Extreme Networks Inc" },
  { ticker: "DGII", name: "Digi International Inc" },
  { ticker: "CALX", name: "Calix Inc" },
  { ticker: "CMBM", name: "Cambium Networks Corporation" },
  { ticker: "ALRM", name: "Alarm.com Holdings Inc" },
  { ticker: "RNG", name: "RingCentral Inc" },
  { ticker: "EGHT", name: "8x8 Inc" },
  { ticker: "FIVN", name: "Five9 Inc" },
  { ticker: "BAND", name: "Bandwidth Inc" },
  { ticker: "AMRX", name: "Amneal Pharmaceuticals Inc" },
  { ticker: "PCRX", name: "Pacira BioSciences Inc" },
  { ticker: "AMPH", name: "Amphastar Pharmaceuticals Inc" },
  { ticker: "JAZZ", name: "Jazz Pharmaceuticals plc" },
  { ticker: "PRGO", name: "Perrigo Company plc" },
  { ticker: "ENDP", name: "Endo International plc" },
  { ticker: "MNK", name: "Mallinckrodt plc" },
  { ticker: "HALO", name: "Halozyme Therapeutics Inc" },
  { ticker: "EXEL", name: "Exelixis Inc" },
  { ticker: "INCY", name: "Incyte Corporation" },
  { ticker: "BMRN", name: "BioMarin Pharmaceutical Inc" },
  { ticker: "UTHR", name: "United Therapeutics Corporation" },
  { ticker: "IONS", name: "Ionis Pharmaceuticals Inc" },
  { ticker: "ALNY", name: "Alnylam Pharmaceuticals Inc" },
  { ticker: "BGNE", name: "BeiGene Ltd" },
  { ticker: "LEGN", name: "Legend Biotech Corporation" },
  { ticker: "ARGX", name: "argenx SE" },
  { ticker: "RYTM", name: "Rhythm Pharmaceuticals Inc" },
  { ticker: "KRYS", name: "Krystal Biotech Inc" },
  { ticker: "BLUE", name: "bluebird bio Inc" },
  { ticker: "CRSP", name: "CRISPR Therapeutics AG" },
  { ticker: "NTLA", name: "Intellia Therapeutics Inc" },
  { ticker: "EDIT", name: "Editas Medicine Inc" },
  { ticker: "BEAM", name: "Beam Therapeutics Inc" },
  { ticker: "VERV", name: "Verve Therapeutics Inc" },
  { ticker: "PRME", name: "Prime Medicine Inc" },
  { ticker: "SANA", name: "Sana Biotechnology Inc" },
  { ticker: "RPTX", name: "Repare Therapeutics Inc" },
  { ticker: "FATE", name: "Fate Therapeutics Inc" },
  { ticker: "CRBU", name: "Caribou Biosciences Inc" },
  { ticker: "VCEL", name: "Vericel Corporation" },
  { ticker: "RGEN", name: "Repligen Corporation" },
  { ticker: "TWST", name: "Twist Bioscience Corporation" },
  { ticker: "PACB", name: "Pacific Biosciences of California Inc" },
  { ticker: "NTRA", name: "Natera Inc" },
  { ticker: "VEEV", name: "Veeva Systems Inc" },
  { ticker: "MEDP", name: "Medpace Holdings Inc" },
  { ticker: "CRL", name: "Charles River Laboratories International Inc" },
  { ticker: "TECH", name: "Bio-Techne Corporation" },
  { ticker: "QGEN", name: "QIAGEN NV" },
  { ticker: "GH", name: "Guardant Health Inc" },
  { ticker: "EXAS", name: "Exact Sciences Corporation" },
  { ticker: "ILMN", name: "Illumina Inc" },
  { ticker: "PODD", name: "Insulet Corporation" },
  { ticker: "TNDM", name: "Tandem Diabetes Care Inc" },
  { ticker: "NVRO", name: "Nevro Corp" },
  { ticker: "AXNX", name: "Axonics Inc" },
  { ticker: "INSP", name: "Inspire Medical Systems Inc" },
  { ticker: "NARI", name: "Inari Medical Inc" },
  { ticker: "PEN", name: "Penumbra Inc" },
  { ticker: "SHC", name: "Sotera Health Company" },
  { ticker: "MASI", name: "Masimo Corporation" },
  { ticker: "ENV", name: "Envestnet Inc" },
  { ticker: "EVR", name: "Evercore Inc" },
  { ticker: "LAZ", name: "Lazard Inc" },
  { ticker: "MC", name: "Moelis & Company" },
  { ticker: "PJT", name: "PJT Partners Inc" },
  { ticker: "HLI", name: "Houlihan Lokey Inc" },
  { ticker: "JEF", name: "Jefferies Financial Group Inc" },
  { ticker: "PIPR", name: "Piper Sandler Companies" },
  { ticker: "SF", name: "Stifel Financial Corp" },
  { ticker: "BCS", name: "Barclays PLC" },
  { ticker: "DB", name: "Deutsche Bank AG" },
  { ticker: "UBS", name: "UBS Group AG" },
  { ticker: "HSBC", name: "HSBC Holdings plc" },
  { ticker: "ING", name: "ING Groep NV" },
  { ticker: "SAN", name: "Banco Santander SA" },
  { ticker: "BBVA", name: "Banco Bilbao Vizcaya Argentaria SA" },
  { ticker: "RY", name: "Royal Bank of Canada" },
  { ticker: "TD", name: "Toronto-Dominion Bank" },
  { ticker: "BMO", name: "Bank of Montreal" },
  { ticker: "BNS", name: "Bank of Nova Scotia" },
  { ticker: "CM", name: "Canadian Imperial Bank of Commerce" },
  { ticker: "MFC", name: "Manulife Financial Corporation" },
  { ticker: "SLF", name: "Sun Life Financial Inc" },
  { ticker: "BX", name: "Blackstone Inc" },
  { ticker: "KKR", name: "KKR & Co Inc" },
  { ticker: "APO", name: "Apollo Global Management Inc" },
  { ticker: "ARES", name: "Ares Management Corporation" },
  { ticker: "BAM", name: "Brookfield Asset Management Ltd" },
  { ticker: "BN", name: "Brookfield Corporation" },
  { ticker: "CG", name: "Carlyle Group Inc" },
  { ticker: "OWL", name: "Blue Owl Capital Inc" },
  { ticker: "HLNE", name: "Hamilton Lane Incorporated" },
  { ticker: "STEP", name: "StepStone Group Inc" },
  { ticker: "PGRE", name: "Paramount Group Inc" },
  { ticker: "VNO", name: "Vornado Realty Trust" },
  { ticker: "SLG", name: "SL Green Realty Corp" },
  { ticker: "PARA", name: "Paramount Global" },
  { ticker: "FOX", name: "Fox Corporation" },
  { ticker: "FOXA", name: "Fox Corporation Class A" },
  { ticker: "NWSA", name: "News Corporation" },
  { ticker: "NYT", name: "New York Times Company" },
  { ticker: "IAC", name: "IAC Inc" },
  { ticker: "ANGI", name: "Angi Inc" },
  { ticker: "TRIP", name: "Tripadvisor Inc" },
  { ticker: "EBAY", name: "eBay Inc" },
  { ticker: "OSTK", name: "Overstock.com Inc" },
  { ticker: "REAL", name: "RealReal Inc" },
  { ticker: "RVLV", name: "Revolve Group Inc" },
  { ticker: "FTCH", name: "Farfetch Limited" },
  { ticker: "VIPS", name: "Vipshop Holdings Limited" },
  { ticker: "JMIA", name: "Jumia Technologies AG" },
  { ticker: "GLBE", name: "Global-E Online Ltd" },
  { ticker: "OLO", name: "Olo Inc" },
  { ticker: "DUOL", name: "Duolingo Inc" },
  { ticker: "COUR", name: "Coursera Inc" },
  { ticker: "CHGG", name: "Chegg Inc" },
  { ticker: "EDU", name: "New Oriental Education & Technology Group Inc" },
  { ticker: "TAL", name: "TAL Education Group" },
  { ticker: "LRN", name: "Stride Inc" },
  { ticker: "INST", name: "Instructure Holdings Inc" },
  { ticker: "POWL", name: "Powell Industries Inc" },
  { ticker: "MTZ", name: "MasTec Inc" },
  { ticker: "PRIM", name: "Primoris Services Corporation" },
  { ticker: "FIX", name: "Comfort Systems USA Inc" },
  { ticker: "AMR", name: "Alpha Metallurgical Resources Inc" },
  { ticker: "ARCH", name: "Arch Resources Inc" },
  { ticker: "BTU", name: "Peabody Energy Corporation" },
  { ticker: "CEIX", name: "CONSOL Energy Inc" },
  { ticker: "METC", name: "Ramaco Resources Inc" },
  { ticker: "HCC", name: "Warrior Met Coal Inc" },
  { ticker: "AR", name: "Antero Resources Corporation" },
  { ticker: "AM", name: "Antero Midstream Corporation" },
  { ticker: "RRC", name: "Range Resources Corporation" },
  { ticker: "SWN", name: "Southwestern Energy Company" },
  { ticker: "CHK", name: "Chesapeake Energy Corporation" },
  { ticker: "CTRA", name: "Coterra Energy Inc" },
  { ticker: "MUR", name: "Murphy Oil Corporation" },
  { ticker: "MRO", name: "Marathon Oil Corporation" },
  { ticker: "OVV", name: "Ovintiv Inc" },
  { ticker: "PR", name: "Permian Resources Corporation" },
  { ticker: "MTDR", name: "Matador Resources Company" },
  { ticker: "VTLE", name: "Vital Energy Inc" },
  { ticker: "CRGY", name: "Crescent Energy Company" },
  { ticker: "CIVI", name: "Civitas Resources Inc" },
  { ticker: "CRC", name: "California Resources Corporation" },
  { ticker: "VIST", name: "Vista Energy SAB de CV" },
  { ticker: "TS", name: "Tenaris SA" },
  { ticker: "RIG", name: "Transocean Ltd" },
  { ticker: "VAL", name: "Valaris Limited" },
  { ticker: "NE", name: "Noble Corporation plc" },
  { ticker: "BORR", name: "Borr Drilling Limited" },
  { ticker: "PTEN", name: "Patterson-UTI Energy Inc" },
  { ticker: "HP", name: "Helmerich & Payne Inc" },
  { ticker: "NBR", name: "Nabors Industries Ltd" },
  { ticker: "WHD", name: "Cactus Inc" },
  { ticker: "LBRT", name: "Liberty Energy Inc" },
  { ticker: "PUMP", name: "ProPetro Holding Corp" },
  { ticker: "NEX", name: "NextEra Energy Partners" },
  { ticker: "WTTR", name: "Select Water Solutions Inc" },
  { ticker: "FTI", name: "TechnipFMC plc" },
  { ticker: "WFRD", name: "Weatherford International plc" },
  { ticker: "CHX", name: "ChampionX Corporation" },
  { ticker: "LNG", name: "Cheniere Energy Inc" },
  { ticker: "CQP", name: "Cheniere Energy Partners LP" },
  { ticker: "TRP", name: "TC Energy Corporation" },
  { ticker: "ENB", name: "Enbridge Inc" },
  { ticker: "EPD", name: "Enterprise Products Partners LP" },
  { ticker: "MPLX", name: "MPLX LP" },
  { ticker: "ET", name: "Energy Transfer LP" },
  { ticker: "WES", name: "Western Midstream Partners LP" },
  { ticker: "PAA", name: "Plains All American Pipeline LP" },
  { ticker: "PAGP", name: "Plains GP Holdings LP" },
  { ticker: "DCP", name: "DCP Midstream LP" },
  { ticker: "AROC", name: "Archrock Inc" },
  { ticker: "USAC", name: "USA Compression Partners LP" },
  { ticker: "NS", name: "NuStar Energy LP" },
  { ticker: "GEL", name: "Genesis Energy LP" },
  { ticker: "GLP", name: "Global Partners LP" },
  { ticker: "MMP", name: "Magellan Midstream Partners" },
  // ─── Más mid-caps con news flow recurrente ─────────────────────────────
  { ticker: "RDNT", name: "RadNet Inc" },
  { ticker: "EVH", name: "Evolent Health Inc" },
  { ticker: "PRMW", name: "Primo Brands Corporation" },
  { ticker: "GPK", name: "Graphic Packaging Holding Company" },
  { ticker: "LUMN", name: "Lumen Technologies Inc" },
  { ticker: "HMC", name: "Honda Motor Company Ltd" },
  { ticker: "TM", name: "Toyota Motor Corporation" },
  { ticker: "STLA", name: "Stellantis NV" },
  { ticker: "RACE", name: "Ferrari NV" },
  { ticker: "POAHY", name: "Porsche Automobil Holding SE" },
  { ticker: "VWAGY", name: "Volkswagen AG" },
  { ticker: "BMWYY", name: "Bayerische Motoren Werke AG" },
  { ticker: "DDAIF", name: "Mercedes-Benz Group AG" },
  { ticker: "NSANY", name: "Nissan Motor Co Ltd" },
  { ticker: "MZDAY", name: "Mazda Motor Corporation" },
  { ticker: "SBGSY", name: "Schneider Electric SE" },
  { ticker: "SIEGY", name: "Siemens AG" },
  { ticker: "PHG", name: "Koninklijke Philips NV" },
  { ticker: "SAP", name: "SAP SE" },
  { ticker: "STM", name: "STMicroelectronics NV" },
  { ticker: "NOK", name: "Nokia Corporation" },
  { ticker: "ERIC", name: "Telefonaktiebolaget LM Ericsson" },
  { ticker: "VOD", name: "Vodafone Group plc" },
  { ticker: "BP", name: "BP plc" },
  { ticker: "SHEL", name: "Shell plc" },
  { ticker: "EQNR", name: "Equinor ASA" },
  { ticker: "E", name: "Eni SpA" },
  { ticker: "TTE", name: "TotalEnergies SE" },
  { ticker: "PBR", name: "Petrobras" },
  { ticker: "RIO", name: "Rio Tinto plc" },
  { ticker: "BHP", name: "BHP Group Limited" },
  { ticker: "VALE", name: "Vale SA" },
  { ticker: "SCCO", name: "Southern Copper Corporation" },
  { ticker: "FCX", name: "Freeport-McMoRan Inc" },
  { ticker: "NEM", name: "Newmont Corporation" },
  { ticker: "GOLD", name: "Barrick Gold Corporation" },
  { ticker: "AEM", name: "Agnico Eagle Mines Limited" },
  { ticker: "KGC", name: "Kinross Gold Corporation" },
  { ticker: "AU", name: "AngloGold Ashanti plc" },
  { ticker: "GFI", name: "Gold Fields Limited" },
  { ticker: "HMY", name: "Harmony Gold Mining Company Limited" },
  { ticker: "IAG", name: "IAMGOLD Corporation" },
  { ticker: "PAAS", name: "Pan American Silver Corp" },
  { ticker: "AG", name: "First Majestic Silver Corp" },
  { ticker: "HL", name: "Hecla Mining Company" },
  { ticker: "CDE", name: "Coeur Mining Inc" },
  { ticker: "MP", name: "MP Materials Corp" },
  { ticker: "LAC", name: "Lithium Americas Corp" },
  { ticker: "LTHM", name: "Livent Corporation" },
  { ticker: "SQM", name: "Sociedad Quimica y Minera de Chile SA" },
  { ticker: "PLL", name: "Piedmont Lithium Inc" },
  { ticker: "SGML", name: "Sigma Lithium Corporation" },
  { ticker: "URA", name: "Global X Uranium ETF" },
  { ticker: "CCJ", name: "Cameco Corporation" },
  { ticker: "UEC", name: "Uranium Energy Corp" },
  { ticker: "DNN", name: "Denison Mines Corp" },
  { ticker: "URG", name: "Ur-Energy Inc" },
  { ticker: "LEU", name: "Centrus Energy Corp" },
  { ticker: "OKLO", name: "Oklo Inc" },
  { ticker: "SMR", name: "NuScale Power Corporation" },
  { ticker: "BWXT", name: "BWX Technologies Inc" },
  { ticker: "GEV", name: "GE Vernova Inc" },
  { ticker: "CEG", name: "Constellation Energy Corporation" },
  { ticker: "VST", name: "Vistra Corp" },
  { ticker: "TLN", name: "Talen Energy Corporation" },
  { ticker: "PCG", name: "PG&E Corporation" },
  { ticker: "SRPT", name: "Sarepta Therapeutics Inc" },
  { ticker: "MRTX", name: "Mirati Therapeutics Inc" },
  { ticker: "BLUE", name: "bluebird bio Inc" },
  { ticker: "RARE", name: "Ultragenyx Pharmaceutical Inc" },
  { ticker: "SMMT", name: "Summit Therapeutics Inc" },
  { ticker: "CRNX", name: "Crinetics Pharmaceuticals Inc" },
  { ticker: "TARS", name: "Tarsus Pharmaceuticals Inc" },
  { ticker: "HRMY", name: "Harmony Biosciences Holdings Inc" },
  { ticker: "AKRO", name: "Akero Therapeutics Inc" },
  { ticker: "MDGL", name: "Madrigal Pharmaceuticals Inc" },
  { ticker: "VKTX", name: "Viking Therapeutics Inc" },
  { ticker: "TGTX", name: "TG Therapeutics Inc" },
  { ticker: "AXSM", name: "Axsome Therapeutics Inc" },
  { ticker: "AGEN", name: "Agenus Inc" },
  { ticker: "IOVA", name: "Iovance Biotherapeutics Inc" },
  { ticker: "NVAX", name: "Novavax Inc" },
  { ticker: "OCGN", name: "Ocugen Inc" },
  { ticker: "INO", name: "Inovio Pharmaceuticals Inc" },
  { ticker: "VXRT", name: "Vaxart Inc" },
  { ticker: "GRTS", name: "Gritstone bio Inc" },
  { ticker: "CYTK", name: "Cytokinetics Incorporated" },
  { ticker: "EWTX", name: "Edgewise Therapeutics Inc" },
  { ticker: "DYN", name: "Dyne Therapeutics Inc" },
  { ticker: "RXRX", name: "Recursion Pharmaceuticals Inc" },
  { ticker: "SDGR", name: "Schrodinger Inc" },
  { ticker: "ABCL", name: "AbCellera Biologics Inc" },
  { ticker: "ABSI", name: "Absci Corporation" },
  { ticker: "TWST", name: "Twist Bioscience Corporation" },
  { ticker: "PRCT", name: "PROCEPT BioRobotics Corporation" },
  { ticker: "TMDX", name: "TransMedics Group Inc" },
  { ticker: "PHIN", name: "Phinia Inc" },
  { ticker: "ADNT", name: "Adient plc" },
  { ticker: "AXL", name: "American Axle & Manufacturing Holdings Inc" },
  { ticker: "MGA", name: "Magna International Inc" },
  { ticker: "APTV", name: "Aptiv PLC" },
  { ticker: "LEA", name: "Lear Corporation" },
  { ticker: "BWA", name: "BorgWarner Inc" },
  { ticker: "DAN", name: "Dana Incorporated" },
  { ticker: "MTOR", name: "Meritor Inc" },
  { ticker: "MOD", name: "Modine Manufacturing Company" },
  { ticker: "GTES", name: "Gates Industrial Corporation plc" },
  { ticker: "AAP", name: "Advance Auto Parts Inc" },
  { ticker: "AZO", name: "AutoZone Inc" },
  { ticker: "GPC", name: "Genuine Parts Company" },
  { ticker: "MNRO", name: "Monro Inc" },
  { ticker: "DORM", name: "Dorman Products Inc" },
  { ticker: "SMP", name: "Standard Motor Products Inc" },
  { ticker: "PII", name: "Polaris Inc" },
  { ticker: "HOG", name: "Harley-Davidson Inc" },
  { ticker: "BC", name: "Brunswick Corporation" },
  { ticker: "MBUU", name: "Malibu Boats Inc" },
  { ticker: "MCFT", name: "MasterCraft Boat Holdings Inc" },
  { ticker: "PATK", name: "Patrick Industries Inc" },
  { ticker: "LCII", name: "LCI Industries" },
  { ticker: "THO", name: "Thor Industries Inc" },
  { ticker: "WGO", name: "Winnebago Industries Inc" },
  { ticker: "CWH", name: "Camping World Holdings Inc" },
  { ticker: "ONEW", name: "OneWater Marine Inc" },
  { ticker: "MARK", name: "Remark Holdings Inc" },
  { ticker: "ELP", name: "Companhia Paranaense de Energia" },
  { ticker: "EBR", name: "Centrais Eletricas Brasileiras SA" },
  { ticker: "CIG", name: "Companhia Energetica de Minas Gerais" },
  { ticker: "SBSW", name: "Sibanye Stillwater Limited" },
  { ticker: "AGCO", name: "AGCO Corporation" },
  { ticker: "BG", name: "Bunge Global SA" },
  { ticker: "ANDE", name: "Andersons Inc" },
  { ticker: "INGR", name: "Ingredion Incorporated" },
  { ticker: "DAR", name: "Darling Ingredients Inc" },
  { ticker: "POST", name: "Post Holdings Inc" },
  { ticker: "BG", name: "Bunge Global SA" },
  { ticker: "SAFM", name: "Sanderson Farms Inc" },
  { ticker: "PPC", name: "Pilgrim's Pride Corporation" },
  { ticker: "CALM", name: "Cal-Maine Foods Inc" },
  { ticker: "HRL", name: "Hormel Foods Corporation" },
  { ticker: "MKC", name: "McCormick & Company Incorporated" },
  { ticker: "SAM", name: "Boston Beer Company Inc" },
  { ticker: "DEO", name: "Diageo plc" },
  { ticker: "ABEV", name: "Ambev SA" },
  { ticker: "BUD", name: "Anheuser-Busch InBev SA/NV" },
  { ticker: "STZ", name: "Constellation Brands Inc" },
  { ticker: "MGPI", name: "MGP Ingredients Inc" },
  { ticker: "FIZZ", name: "National Beverage Corp" },
  { ticker: "CELH", name: "Celsius Holdings Inc" },
  { ticker: "VITL", name: "Vital Farms Inc" },
  { ticker: "FRPT", name: "Freshpet Inc" },
  { ticker: "CHEF", name: "Chefs' Warehouse Inc" },
  { ticker: "USFD", name: "US Foods Holding Corp" },
  { ticker: "PFGC", name: "Performance Food Group Company" },
  { ticker: "AMRC", name: "Ameresco Inc" },
  { ticker: "ARRY", name: "Array Technologies Inc" },
  { ticker: "SHLS", name: "Shoals Technologies Group Inc" },
  { ticker: "FLNC", name: "Fluence Energy Inc" },
  { ticker: "STEM", name: "Stem Inc" },
  { ticker: "ENS", name: "EnerSys" },
  { ticker: "EOSE", name: "Eos Energy Enterprises Inc" },
  { ticker: "GEVO", name: "Gevo Inc" },
  { ticker: "AMRS", name: "Amyris Inc" },
  { ticker: "CDLR", name: "Cadeler A/S" },
  { ticker: "TPIC", name: "TPI Composites Inc" },
  { ticker: "ICLN", name: "iShares Global Clean Energy ETF" },
  { ticker: "NEE", name: "NextEra Energy Inc" },
  // ─── Final adds — companies frecuentemente mencionadas en FT/Bloomberg ──
  { ticker: "RKT", name: "Rocket Companies Inc" },
  { ticker: "UWMC", name: "UWM Holdings Corporation" },
  { ticker: "PHH", name: "Mr Cooper Group Inc" },
  { ticker: "NMIH", name: "NMI Holdings Inc" },
  { ticker: "MTG", name: "MGIC Investment Corporation" },
  { ticker: "ESNT", name: "Essent Group Ltd" },
  { ticker: "RDN", name: "Radian Group Inc" },
  { ticker: "BPOP", name: "Popular Inc" },
  { ticker: "VLY", name: "Valley National Bancorp" },
  { ticker: "WBS", name: "Webster Financial Corporation" },
  { ticker: "FCNCA", name: "First Citizens BancShares Inc" },
  { ticker: "CMA", name: "Comerica Incorporated" },
  { ticker: "EWBC", name: "East West Bancorp Inc" },
  { ticker: "PNFP", name: "Pinnacle Financial Partners Inc" },
  { ticker: "SNV", name: "Synovus Financial Corp" },
  { ticker: "UMBF", name: "UMB Financial Corporation" },
  { ticker: "ONB", name: "Old National Bancorp" },
  { ticker: "BOH", name: "Bank of Hawaii Corporation" },
  { ticker: "FBP", name: "First BanCorp" },
  { ticker: "TCBI", name: "Texas Capital Bancshares Inc" },
  { ticker: "SBNY", name: "Signature Bank" },
  { ticker: "SIVB", name: "SVB Financial Group" },
  { ticker: "FRC", name: "First Republic Bank" },
  { ticker: "PACW", name: "PacWest Bancorp" },
  { ticker: "WAL", name: "Western Alliance Bancorporation" },
  { ticker: "TWO", name: "Two Harbors Investment Corp" },
  { ticker: "AGNC", name: "AGNC Investment Corp" },
  { ticker: "NLY", name: "Annaly Capital Management Inc" },
  { ticker: "STWD", name: "Starwood Property Trust Inc" },
  { ticker: "BXMT", name: "Blackstone Mortgage Trust Inc" },
  { ticker: "ABR", name: "Arbor Realty Trust Inc" },
  { ticker: "LADR", name: "Ladder Capital Corp" },
  { ticker: "RWT", name: "Redwood Trust Inc" },
  { ticker: "MITT", name: "AG Mortgage Investment Trust Inc" },
  { ticker: "NREF", name: "NexPoint Real Estate Finance Inc" },
  { ticker: "MBIN", name: "Merchants Financial Group Inc" },
  { ticker: "OCFC", name: "OceanFirst Financial Corp" },
  { ticker: "WSBC", name: "WesBanco Inc" },
  { ticker: "GBCI", name: "Glacier Bancorp Inc" },
  { ticker: "BANR", name: "Banner Corporation" },
  { ticker: "WAFD", name: "WaFd Inc" },
  { ticker: "TRMK", name: "Trustmark Corporation" },
  { ticker: "FFBC", name: "First Financial Bancorp" },
  { ticker: "INDB", name: "Independent Bank Corp" },
  { ticker: "COLB", name: "Columbia Banking System Inc" },
  { ticker: "UCBI", name: "United Community Banks Inc" },
  { ticker: "FBNC", name: "First Bancorp" },
  { ticker: "SFBS", name: "ServisFirst Bancshares Inc" },
  { ticker: "MBI", name: "MBIA Inc" },
  { ticker: "AMBC", name: "Ambac Financial Group Inc" },
  { ticker: "AGO", name: "Assured Guaranty Ltd" },
  { ticker: "MGI", name: "MoneyGram International Inc" },
  { ticker: "EVTC", name: "EVERTEC Inc" },
  { ticker: "PAYO", name: "Payoneer Global Inc" },
  { ticker: "FOUR", name: "Shift4 Payments Inc" },
  { ticker: "FLYW", name: "Flywire Corporation" },
  { ticker: "WEX", name: "WEX Inc" },
  { ticker: "EEFT", name: "Euronet Worldwide Inc" },
  { ticker: "CASH", name: "Pathward Financial Inc" },
  { ticker: "GDOT", name: "Green Dot Corporation" },
  { ticker: "ALLY", name: "Ally Financial Inc" },
  { ticker: "NAVI", name: "Navient Corporation" },
  { ticker: "SLM", name: "SLM Corporation" },
  { ticker: "NNI", name: "Nelnet Inc" },
  { ticker: "OMF", name: "OneMain Holdings Inc" },
  { ticker: "WRLD", name: "World Acceptance Corporation" },
  { ticker: "ENVA", name: "Enova International Inc" },
  { ticker: "PRAA", name: "PRA Group Inc" },
  { ticker: "ECPG", name: "Encore Capital Group Inc" },
  // Specialty Industrials & Materials
  { ticker: "ATR", name: "AptarGroup Inc" },
  { ticker: "BERY", name: "Berry Global Group Inc" },
  { ticker: "CCK", name: "Crown Holdings Inc" },
  { ticker: "OI", name: "O-I Glass Inc" },
  { ticker: "GEF", name: "Greif Inc" },
  { ticker: "SLGN", name: "Silgan Holdings Inc" },
  { ticker: "ARMK", name: "Aramark" },
  { ticker: "ABM", name: "ABM Industries Incorporated" },
  { ticker: "CWST", name: "Casella Waste Systems Inc" },
  { ticker: "WCN", name: "Waste Connections Inc" },
  { ticker: "WAST", name: "Waste Management Inc" },
  { ticker: "GFL", name: "GFL Environmental Inc" },
  { ticker: "STN", name: "Stantec Inc" },
  { ticker: "WSP", name: "WSP Global Inc" },
  { ticker: "ACM", name: "AECOM" },
  { ticker: "EME", name: "EMCOR Group Inc" },
  { ticker: "MTH", name: "Meritage Homes Corporation" },
  { ticker: "TPH", name: "Tri Pointe Homes Inc" },
  { ticker: "TMHC", name: "Taylor Morrison Home Corporation" },
  { ticker: "MDC", name: "M.D.C. Holdings Inc" },
  { ticker: "GRBK", name: "Green Brick Partners Inc" },
  { ticker: "BZH", name: "Beazer Homes USA Inc" },
  { ticker: "KBH", name: "KB Home" },
  { ticker: "CCS", name: "Century Communities Inc" },
  { ticker: "LGIH", name: "LGI Homes Inc" },
  { ticker: "DFH", name: "Dream Finders Homes Inc" },
  { ticker: "HOV", name: "Hovnanian Enterprises Inc" },
  { ticker: "USG", name: "USG Corporation" },
  { ticker: "EXP", name: "Eagle Materials Inc" },
  { ticker: "SUM", name: "Summit Materials Inc" },
  { ticker: "USCR", name: "U.S. Concrete Inc" },
  { ticker: "MAS", name: "Masco Corporation" },
  { ticker: "FBHS", name: "Fortune Brands Innovations Inc" },
  { ticker: "AOS", name: "A.O. Smith Corporation" },
  { ticker: "WSO", name: "Watsco Inc" },
  { ticker: "LII", name: "Lennox International Inc" },
  { ticker: "RXO", name: "RXO Inc" },
  { ticker: "GXO", name: "GXO Logistics Inc" },
  { ticker: "FWRD", name: "Forward Air Corporation" },
  { ticker: "MATX", name: "Matson Inc" },
  { ticker: "KEX", name: "Kirby Corporation" },
  { ticker: "GBX", name: "Greenbrier Companies Inc" },
  { ticker: "TRN", name: "Trinity Industries Inc" },
  { ticker: "WAB", name: "Westinghouse Air Brake Technologies Corporation" },
  { ticker: "CP", name: "Canadian Pacific Kansas City Limited" },
  { ticker: "CNI", name: "Canadian National Railway Company" },
  { ticker: "GATX", name: "GATX Corporation" },
  // News/Subscription/SaaS Common in FT
  { ticker: "NEWR", name: "New Relic Inc" },
  { ticker: "SUMO", name: "Sumo Logic Inc" },
  { ticker: "DBX", name: "Dropbox Inc" },
  { ticker: "BOX", name: "Box Inc" },
  { ticker: "EVBG", name: "Everbridge Inc" },
  { ticker: "ZUO", name: "Zuora Inc" },
  { ticker: "DOMO", name: "Domo Inc" },
  { ticker: "ALKT", name: "Alkami Technology Inc" },
  { ticker: "NTNX", name: "Nutanix Inc" },
  { ticker: "RPD", name: "Rapid7 Inc" },
  { ticker: "CYBR", name: "CyberArk Software Ltd" },
  { ticker: "VRNS", name: "Varonis Systems Inc" },
  { ticker: "TENB", name: "Tenable Holdings Inc" },
  { ticker: "QLYS", name: "Qualys Inc" },
  { ticker: "MIME", name: "Mimecast Limited" },
  { ticker: "FSLY", name: "Fastly Inc" },
  { ticker: "AKAM", name: "Akamai Technologies Inc" },
  { ticker: "AI", name: "C3.ai Inc" },
  { ticker: "BBAI", name: "BigBear.ai Holdings Inc" },
  { ticker: "SOUN", name: "SoundHound AI Inc" },
  { ticker: "AISP", name: "Airship AI Holdings Inc" },
  { ticker: "AGFY", name: "Agrify Corporation" },
  { ticker: "VERI", name: "Veritone Inc" },
  { ticker: "NBIS", name: "Nebius Group NV" },
  // Cap final
];

// Quita sufijos corporativos comunes de un nombre para obtener un alias
// "limpio" que matchee mejor en headlines (ej. "Microsoft Corporation" →
// "Microsoft"). El extractor también acepta el nombre original.
function stripSuffix(name: string): string {
  return name
    .replace(
      // Sufijos comunes (case-insensitive). El orden importa solo
      // para evitar dobles strips raros; usamos /g porque algunos nombres
      // arrastran dos suffix ("Inc PLC" raro pero existe).
      /\b(Inc\.?|Incorporated|Corp\.?|Corporation|Company|Companies|Co\.?|Ltd\.?|Limited|PLC|N\.?V\.?|S\.?A\.?|S\.?A\.?B\.?(\sde\sCV)?|A\/S|AG|ASA|SE|Group|Holdings|Holding|plc)\b/gi,
      "",
    )
    .replace(/[,]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    // Clean trailing connectors left dangling after suffix strip:
    //   "JPMorgan Chase & Co" -> "JPMorgan Chase &" -> "JPMorgan Chase"
    //   "Eli Lilly and Company" -> "Eli Lilly and" -> "Eli Lilly"
    // Loop because some names need multiple passes ("X and & Co").
    .replace(/[\s,&]+(and|&)?[\s,&]*$/gi, "")
    .replace(/[\s,]+$/g, "")
    .trim();
}

// Genera el set de aliases a insertar para un seed. Reglas:
//   1) Nombre original tal cual (si ≥3 chars).
//   2) Nombre con suffix stripped (si distinto del original y ≥3 chars).
// Filtramos contra el denylist del extractor. NO añadimos "first word" porque
// el enricher ya lo hace cuando un ticker pasa por Finnhub — duplicar aquí
// metería ruido sin restricciones de longitud que ya están en enricher.
function aliasesFor(name: string): string[] {
  const out = new Set<string>();
  const original = name.trim();
  const stripped = stripSuffix(name);
  for (const candidate of [original, stripped]) {
    if (!candidate) continue;
    if (candidate.length < 3) continue;
    if (ALIAS_DENYLIST.has(candidate.toLowerCase())) continue;
    out.add(candidate);
  }
  return Array.from(out);
}

async function main() {
  const dryRun = process.argv.includes("--dry-run");

  // Dedupe por (alias, ticker) y por ticker para minimizar round-trips.
  const tickersToSeed = new Map<string, string>(); // symbol → name
  const aliasPairs = new Set<string>(); // "alias|||symbol"
  for (const seed of SEEDS) {
    const sym = seed.ticker.trim().toUpperCase();
    if (!sym) continue;
    if (!tickersToSeed.has(sym)) tickersToSeed.set(sym, seed.name);
    const aliases = aliasesFor(seed.name);
    for (const a of aliases) {
      aliasPairs.add(`${a}|||${sym}`);
    }
  }

  const totalAliasCandidates = aliasPairs.size;
  // Métrica para el reporte: cuántos aliases caen en API_ONLY (insertarlos
  // no hace daño — el extractor los skip-ea — pero los contamos aparte).
  let apiOnlyCount = 0;
  for (const pair of aliasPairs) {
    const sym = pair.split("|||")[1];
    if (API_ONLY.has(sym)) apiOnlyCount++;
  }

  console.log(
    `[seed-aliases] ${SEEDS.length} seeds → ${tickersToSeed.size} unique tickers, ${totalAliasCandidates} alias pairs (${apiOnlyCount} API_ONLY)`,
  );

  if (dryRun) {
    console.log("[seed-aliases] DRY RUN — printing first 20 pairs:");
    let i = 0;
    for (const pair of aliasPairs) {
      if (i++ >= 20) break;
      const [alias, symbol] = pair.split("|||");
      console.log(`  ${symbol.padEnd(8)} ← "${alias}"`);
    }
    console.log("[seed-aliases] DRY RUN complete. No DB writes.");
    process.exit(0);
  }

  const { db } = await import("../lib/db");
  const { tickers, tickerAliases } = await import("../lib/db/schema");

  // Batched inserts. Sequential one-by-one with .returning() was ~70
  // rows/min over Neon (each row a full TCP round-trip via PgBouncer
  // transaction mode). Multi-row VALUES dropped the wall-clock from
  // ~25min to ~30s for the same payload.
  const CHUNK = 100;

  // 1) Parent tickers first (FK constraint on ticker_aliases.symbol).
  const tickerRows = Array.from(tickersToSeed.entries()).map(
    ([symbol, name]) => ({ symbol, name, source: "seed-aliases" }),
  );
  let tickerInserted = 0;
  for (let i = 0; i < tickerRows.length; i += CHUNK) {
    const chunk = tickerRows.slice(i, i + CHUNK);
    const res = await db
      .insert(tickers)
      .values(chunk)
      .onConflictDoNothing()
      .returning({ symbol: tickers.symbol });
    tickerInserted += res.length;
  }
  console.log(
    `[seed-aliases] tickers: ${tickerInserted} new / ${tickersToSeed.size - tickerInserted} existed`,
  );

  // 2) Aliases. Same batching pattern; samples are the first few rows
  // we get back from `.returning()` so we don't need a separate sample
  // query.
  const aliasRows = Array.from(aliasPairs).map((pair) => {
    const [alias, symbol] = pair.split("|||");
    return { alias, symbol };
  });
  let aliasInserted = 0;
  const samples: { alias: string; symbol: string }[] = [];
  for (let i = 0; i < aliasRows.length; i += CHUNK) {
    const chunk = aliasRows.slice(i, i + CHUNK);
    const res = await db
      .insert(tickerAliases)
      .values(chunk)
      .onConflictDoNothing()
      .returning({ alias: tickerAliases.alias, symbol: tickerAliases.symbol });
    aliasInserted += res.length;
    for (const r of res) {
      if (samples.length < 5) samples.push(r);
    }
  }
  const aliasSkipped = aliasRows.length - aliasInserted;

  console.log(
    `[seed-aliases] aliases: ${aliasInserted} inserted / ${aliasSkipped} skipped (already existed)`,
  );
  console.log(`[seed-aliases] sample new aliases:`);
  for (const s of samples) {
    console.log(`  ${s.symbol.padEnd(8)} ← "${s.alias}"`);
  }

  console.log(`[seed-aliases] DONE.`);
  process.exit(0);
}

main().catch((err) => {
  console.error("[seed-aliases] FAILED:", err);
  process.exit(1);
});
